workflows:
  flutter-build:
    name: Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
        working_directory: .
      - name: Build APK
        script: flutter build apk --release
        working_directory: .
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - jirensama96000@gmail.com
